
-- Add premium fields to the profiles table
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS premium BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS premium_since TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS premium_expires TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT;
