
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tayixoptbsbgzdcvbcad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheWl4b3B0YnNiZ3pkY3ZiY2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDUzOTIsImV4cCI6MjA1NjY4MTM5Mn0.4N6lBAZyIASnOru9AE9jwJwT6yZ1UWzyIHxKG_Ylj_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create supabase client with enhanced realtime configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 20, // Increased event rate
      }
    },
    db: {
      schema: 'public'
    },
    global: {
      headers: {
        'x-application-name': 'tradetracker'
      },
    },
  }
);

// Configure realtime subscriptions for the relevant tables
supabase.realtime.setRelTime(true);
